version: 2

updates:
  - package-ecosystem: gitsubmodule
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
